# Generated by Django 4.0.5 on 2022-06-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=60, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
