export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const EMPTY_CART = "EMPTY_CART";
export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
export const UPDATE_CART = "UPDATE_CART";
