export const FAVORITE_LIST_REQUEST = "FAVORITE_LIST_REQUEST";
export const FAVORITE_LIST_SUCCESS = "FAVORITE_LIST_SUCCESS";
export const FAVORITE_LIST_FAIL = "FAVORITE_LIST_FAIL";

export const ADD_FAVORITE_LIST = "ADD_FAVORITE_LIST";
export const REMOVE_FAVORITE_LIST = "REMOVE_FAVORITE_LIST";
