export const SET_ORDER_INFO = "SET_ORDER_INFO";
export const GET_ORDER_INFO = "GET_ORDER_INFO";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
