export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const SALE_LIST_REQUEST = "SALE_LIST_REQUEST";
export const SALE_LIST_SUCCESS = "SALE_LIST_SUCCESS";
export const SALE_LIST_FAIL = "SALE_LIST_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const EMPTY_PRODUCT_DETAIL = "EMPTY_PRODUCT_DETAIL";
