export const USER_REVIEW_LIST_REQUEST = "USER_REVIEW_LIST_REQUEST";
export const USER_REVIEW_LIST_SUCCESS = "USER_REVIEW_LIST_SUCCESS";
export const USER_REVIEW_LIST_FAIL = "USER_REVIEW_LIST_FAIL";

export const GET_USER_REVIEW_REQUEST = "GET_USER_REVIEW_REQUEST";
export const GET_USER_REVIEW_SUCCESS = "GET_USER_REVIEW_SUCCESS";
export const GET_USER_REVIEW_FAIL = "GET_USER_REVIEW_FAIL";
